import * as oauthv1Api from './oauthv1';
// import * as userv1 from './userv1';
// import * as miscv1 from './miscv1';
import * as programv2Api from './programv2';
export const oauthv1 = oauthv1Api;
// export const userv1 = userv1Api;
// export const miscv1 = miscv1Api;
export const programv2 = programv2Api;
// export { oauthv1 };
// export { oauthv1, userv1, miscv1, programv2};